name: diamonds_env

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pyarrow
  - joblib
  - pip
  - pip:
      - pandas
      - numpy
      - scikit-learn==1.3.2
      - mltable
      - azure-identity
      - mlflow==2.15.1
      - azureml-mlflow==1.56.0
      - azure-ai-ml==1.21.1